package com.mbd.cmsdesktop.sync

internal class Case(
    val remote: String,
    val local: String,
    val seed: List<String>,
    /** Rows expected in the local table after the first refresh. */
    val expectSeed: Int,
    val insert: String,
    /** Sets a column to a marker value on one existing row; [probe] then counts local rows carrying the marker. */
    val update: String,
    val probe: String,
    val delete: String,
    /** Local-side filter for counting (e.g. only a period's own rows). */
    val countWhere: String = "isDeleted = 0",
    /** Independent checkpoint scopes the app keeps for this table (notifications: one per role). */
    val scopes: Int = 1,
)

internal val syncCases = listOf(
    Case("profiles", "administrator_accounts",
        listOf(
            "do $$ begin insert into auth.users(id,email) values (gen_random_uuid(),'a1@x.pk'); update profiles set role='ADMIN' where email='a1@x.pk'; end $$",
            "do $$ begin insert into auth.users(id,email) values (gen_random_uuid(),'a2@x.pk'); update profiles set role='ADMIN' where email='a2@x.pk'; end $$",
            "do $$ begin insert into auth.users(id,email) values (gen_random_uuid(),'avic@x.pk'); update profiles set role='ADMIN' where email='avic@x.pk'; end $$",
            "insert into auth.users(id,email) values (gen_random_uuid(),'student@x.pk')",
        ), 3,
        "do $$ begin insert into auth.users(id,email) values (gen_random_uuid(),'a3@x.pk'); update profiles set role='ADMIN' where email='a3@x.pk'; end $$",
        "update profiles set status='DISABLED' where email='a1@x.pk'",
        "select count(*) from administrator_accounts where status='DISABLED'",
        "update profiles set is_deleted=true where email='avic@x.pk'"),
    Case("departments", "departments",
        listOf("insert into departments(dept_id,name,code) values ('ch','Chemistry','CH')", "insert into departments(dept_id,name,code) values ('ur','Urdu','UR')", "insert into departments(dept_id,name,code) values ('vic','Victim','VIC')"), 3,
        "insert into departments(dept_id,name,code) values ('ph','Physics','PH')",
        "update departments set name='UPD' where dept_id='ch'",
        "select count(*) from departments where name='UPD'",
        "update departments set is_deleted=true where dept_id='vic'"),
    Case("buildings", "buildings",
        listOf("insert into buildings(building_id,name,code) values ('b1','Main','MB')", "insert into buildings(building_id,name,code) values ('bvic','Victim','VB')"), 2,
        "insert into buildings(building_id,name,code) values ('b2','Annex','AX')",
        "update buildings set name='UPD' where building_id='b1'",
        "select count(*) from buildings where name='UPD'",
        "update buildings set is_deleted=true where building_id='bvic'"),
    Case("rooms", "rooms",
        listOf("insert into rooms(room_id,building_id,room_no,name) values ('r1','b1','R14','Room 14')", "insert into rooms(room_id,building_id,room_no,name) values ('r2','b1','R15','Room 15')", "insert into rooms(room_id,building_id,room_no,name) values ('rvic','b1','R99','Victim')"), 3,
        "insert into rooms(room_id,building_id,room_no,name) values ('r3','b1','R16','Room 16')",
        "update rooms set name='UPD' where room_id='r1'",
        "select count(*) from rooms where name='UPD'",
        "update rooms set is_deleted=true where room_id='rvic'"),
    Case("teachers", "teachers",
        listOf("insert into teachers(email,name,dept_id) values ('t1@x.pk','Teacher One','ch')", "insert into teachers(email,name,dept_id) values ('t2@x.pk','Teacher Two','ur')", "insert into teachers(email,name,dept_id) values ('tvic@x.pk','Victim','ch')"), 3,
        "insert into teachers(email,name,dept_id) values ('t3@x.pk','Teacher Three','ch')",
        "update teachers set name='UPD' where email='t1@x.pk'",
        "select count(*) from teachers where name='UPD'",
        "update teachers set is_deleted=true where email='tvic@x.pk'"),
    Case("academic_sessions", "academic_sessions",
        listOf(
            "insert into academic_sessions(session_id,dept_id,start_year,end_year,max_students,current_semester,shift_mode,program_type) values ('ch_2023','ch',2023,2027,50,3,'MORNING','BS')",
            "insert into academic_sessions(session_id,dept_id,start_year,end_year,max_students,current_semester,shift_mode,program_type) values ('ur_2023','ur',2023,2027,50,3,'MORNING','BS')",
            "insert into academic_sessions(session_id,dept_id,start_year,end_year,max_students,current_semester,shift_mode,program_type) values ('ch_2024','ch',2024,2028,50,1,'MORNING','BS')",
        ), 3,
        "insert into academic_sessions(session_id,dept_id,start_year,end_year,max_students,current_semester,shift_mode,program_type) values ('ur_2024','ur',2024,2028,50,1,'MORNING','BS')",
        "update academic_sessions set program_name='UPD' where session_id='ch_2023'",
        "select count(*) from academic_sessions where programName='UPD'",
        "update academic_sessions set is_deleted=true where session_id='ch_2024'"),
    Case("session_students", "session_students",
        listOf(
            "insert into session_students(session_id,roll_number,name,shift) values ('ch_2023','R-01','Ali','MORNING')",
            "insert into session_students(session_id,roll_number,name,shift) values ('ch_2023','R-02','Sara','MORNING')",
            "insert into session_students(session_id,roll_number,name,shift) values ('ch_2023','R-03','Victim','MORNING')",
            "insert into session_students(session_id,roll_number,name,shift) values ('ur_2023','R-01','Omar','MORNING')",
        ), 4,
        "insert into session_students(session_id,roll_number,name,shift) values ('ch_2023','R-04','Newbie','MORNING')",
        "update session_students set name='UPD' where session_id='ch_2023' and roll_number='R-01'",
        "select count(*) from session_students where name='UPD'",
        "update session_students set is_deleted=true where session_id='ch_2023' and roll_number='R-03'"),
    Case("session_subjects", "semester_subjects",
        listOf(
            "insert into subject_pool(course_code,name,credit_hours) values ('GE-101','English',3),('GE-102','Maths',3),('GE-103','Victim',3),('GE-104','Physics',3) on conflict (course_code) do nothing",
            "insert into session_subjects(session_id,semester,course_code) values ('ch_2023',3,'GE-101')",
            "insert into session_subjects(session_id,semester,course_code) values ('ch_2023',3,'GE-102')",
            "insert into session_subjects(session_id,semester,course_code) values ('ch_2023',3,'GE-103')",
        ), 3,
        "insert into session_subjects(session_id,semester,course_code) values ('ch_2023',3,'GE-104')",
        "update session_subjects set is_elective=true where session_id='ch_2023' and semester=3 and course_code='GE-101'",
        "select count(*) from semester_subjects where courseCode='GE-101' and isElective=1",
        "update session_subjects set is_deleted=true where session_id='ch_2023' and semester=3 and course_code='GE-103'"),
    Case("semester_terms", "semester_terms",
        listOf(
            "insert into semester_terms(session_id,semester,start_date,end_date) values ('ch_2023',3,'2026-01-01','2026-05-01')",
            "insert into semester_terms(session_id,semester,start_date,end_date) values ('ch_2023',4,'2026-06-01','2026-10-01')",
            "insert into semester_terms(session_id,semester,start_date,end_date) values ('ur_2023',3,'2026-01-01','2026-05-01')",
        ), 3,
        "insert into semester_terms(session_id,semester,start_date,end_date) values ('ur_2023',4,'2026-06-01','2026-10-01')",
        "update semester_terms set start_date='2026-02-02' where session_id='ch_2023' and semester=3",
        "select count(*) from semester_terms where startDate='2026-02-02'",
        "update semester_terms set is_deleted=true where session_id='ur_2023' and semester=3"),
    Case("timetable_periods", "session_periods",
        listOf(
            "insert into timetable_periods(primary_session_id,day,start_time,end_time,course_code,subject_name,teacher_email,room_no,shift) values ('ch_2023','MONDAY','09:00','10:00','GE-101','English','t1@x.pk','R1','MORNING')",
            "insert into timetable_periods(primary_session_id,day,start_time,end_time,course_code,subject_name,teacher_email,room_no,shift) values ('ch_2023','TUESDAY','09:00','10:00','GE-102','Maths','t1@x.pk','R1','MORNING')",
            "insert into timetable_periods(primary_session_id,day,start_time,end_time,course_code,subject_name,teacher_email,room_no,shift) values ('ch_2023','WEDNESDAY','09:00','10:00','GE-103','Victim','t1@x.pk','R1','MORNING')",
            "insert into period_sessions(period_id,session_id) select id,'ur_2023' from timetable_periods where day='MONDAY'",
        ), 3,
        "insert into timetable_periods(primary_session_id,day,start_time,end_time,course_code,subject_name,teacher_email,room_no,shift) values ('ch_2023','FRIDAY','09:00','10:00','GE-104','Physics','t1@x.pk','R1','MORNING')",
        "update timetable_periods set room_no='UPD' where day='TUESDAY'",
        "select count(*) from session_periods where roomNo='UPD'",
        "update timetable_periods set is_deleted=true where day='WEDNESDAY'",
        countWhere = "isDeleted = 0 and id = remotePeriodId"),
    Case("calendar_events", "calendar_events",
        listOf(
            "insert into calendar_events(title,event_type,start_date) values ('Sports Day','EVENT','2026-10-01')",
            "insert into calendar_events(title,event_type,start_date) values ('Eid Break','HOLIDAY','2026-10-05')",
            "insert into calendar_events(title,event_type,start_date) values ('Victim','EVENT','2026-10-09')",
        ), 3,
        "insert into calendar_events(title,event_type,start_date) values ('Convocation','EVENT','2026-11-01')",
        "update calendar_events set title='UPD' where title='Sports Day'",
        "select count(*) from calendar_events where title='UPD'",
        "update calendar_events set is_deleted=true where title='Victim'"),
    Case("datesheets", "datesheets",
        listOf(
            "insert into datesheets(id,session_id,semester,shift) values ('11111111-1111-1111-1111-111111111111','ch_2023',3,'MORNING')",
            "insert into datesheets(id,session_id,semester,shift) values ('22222222-2222-2222-2222-222222222222','ur_2023',3,'MORNING')",
            "insert into datesheets(id,session_id,semester,shift) values ('33333333-3333-3333-3333-333333333333','ch_2024',1,'MORNING')",
        ), 3,
        "insert into datesheets(id,session_id,semester,shift) values ('44444444-4444-4444-4444-444444444444','ur_2024',1,'MORNING')",
        "update datesheets set instructions='UPD' where id='11111111-1111-1111-1111-111111111111'",
        "select count(*) from datesheets where instructions='UPD'",
        "update datesheets set is_deleted=true where id='33333333-3333-3333-3333-333333333333'"),
    Case("datesheet_slots", "datesheet_slots",
        listOf(
            "insert into datesheet_slots(datesheet_id,exam_date,start_time,end_time,course_code,subject_name) values ('11111111-1111-1111-1111-111111111111','2026-12-01','09:00','12:00','GE-101','English')",
            "insert into datesheet_slots(datesheet_id,exam_date,start_time,end_time,course_code,subject_name) values ('11111111-1111-1111-1111-111111111111','2026-12-02','09:00','12:00','GE-102','Maths')",
            "insert into datesheet_slots(datesheet_id,exam_date,start_time,end_time,course_code,subject_name) values ('22222222-2222-2222-2222-222222222222','2026-12-03','09:00','12:00','UR-201','Victim')",
        ), 3,
        "insert into datesheet_slots(datesheet_id,exam_date,start_time,end_time,course_code,subject_name) values ('22222222-2222-2222-2222-222222222222','2026-12-04','09:00','12:00','UR-202','Poetry')",
        "update datesheet_slots set subject_name='UPD' where course_code='GE-101'",
        "select count(*) from datesheet_slots where subjectName='UPD'",
        "update datesheet_slots set is_deleted=true where course_code='UR-201'"),
    Case("mark_edit_requests", "mark_edit_requests",
        listOf(
            "insert into mark_edit_requests(session_id,semester,course_code,exam_type,roll_number,current_score,requested_score,requested_by) values ('ch_2023',3,'GE-101','MIDTERM','R-01',10,12,'t1@x.pk')",
            "insert into mark_edit_requests(session_id,semester,course_code,exam_type,roll_number,current_score,requested_score,requested_by) values ('ch_2023',3,'GE-101','MIDTERM','R-02',11,13,'t1@x.pk')",
            "insert into mark_edit_requests(session_id,semester,course_code,exam_type,roll_number,current_score,requested_score,requested_by) values ('ch_2023',3,'GE-102','MIDTERM','R-01',9,14,'t1@x.pk')",
        ), 3,
        "insert into mark_edit_requests(session_id,semester,course_code,exam_type,roll_number,current_score,requested_score,requested_by) values ('ch_2023',3,'GE-102','MIDTERM','R-02',8,15,'t1@x.pk')",
        "update mark_edit_requests set requested_score=24 where course_code='GE-101' and roll_number='R-01'",
        "select count(*) from mark_edit_requests where requestedScore=24",
        "update mark_edit_requests set is_deleted=true where course_code='GE-102' and roll_number='R-01'"),
    Case("session_attendance", "session_attendance_rows",
        listOf(
            "insert into session_attendance(session_id,semester,course_code,date,roll_number,status) values ('ch_2023',3,'GE-101','2026-09-01','R-01','PRESENT')",
            "insert into session_attendance(session_id,semester,course_code,date,roll_number,status) values ('ch_2023',3,'GE-101','2026-09-01','R-02','ABSENT')",
            "insert into session_attendance(session_id,semester,course_code,date,roll_number,status) values ('ch_2023',3,'GE-101','2026-09-01','R-03','PRESENT')",
        ), 3,
        "insert into session_attendance(session_id,semester,course_code,date,roll_number,status) values ('ch_2023',3,'GE-101','2026-09-02','R-01','PRESENT')",
        "update session_attendance set remark='UPD' where roll_number='R-01' and date='2026-09-01'",
        "select count(*) from session_attendance_rows where remark='UPD'",
        "update session_attendance set is_deleted=true where roll_number='R-03'"),
    Case("session_marks", "session_marks",
        listOf(
            "insert into session_marks(session_id,semester,course_code,exam_type,roll_number,score,max_marks) values ('ch_2023',3,'GE-101','MIDTERM','R-01',10,25)",
            "insert into session_marks(session_id,semester,course_code,exam_type,roll_number,score,max_marks) values ('ch_2023',3,'GE-101','MIDTERM','R-02',11,25)",
            "insert into session_marks(session_id,semester,course_code,exam_type,roll_number,score,max_marks) values ('ch_2023',3,'GE-101','MIDTERM','R-03',12,25)",
        ), 3,
        "insert into session_marks(session_id,semester,course_code,exam_type,roll_number,score,max_marks) values ('ch_2023',3,'GE-102','MIDTERM','R-01',13,25)",
        "update session_marks set score=24 where roll_number='R-01' and course_code='GE-101'",
        "select count(*) from session_marks where score=24",
        "update session_marks set is_deleted=true where roll_number='R-03' and course_code='GE-101'"),
    Case("student_semester_gpa", "student_semester_gpa",
        listOf(
            "insert into student_semester_gpa(session_id,roll_number,semester,gpa,cgpa) values ('ch_2023','R-01',1,3.1,3.1)",
            "insert into student_semester_gpa(session_id,roll_number,semester,gpa,cgpa) values ('ch_2023','R-02',1,3.2,3.2)",
            "insert into student_semester_gpa(session_id,roll_number,semester,gpa,cgpa) values ('ch_2023','R-03',1,3.3,3.3)",
        ), 3,
        "insert into student_semester_gpa(session_id,roll_number,semester,gpa,cgpa) values ('ch_2023','R-01',2,3.4,3.25)",
        "update student_semester_gpa set gpa=3.9 where roll_number='R-01' and semester=1",
        "select count(*) from student_semester_gpa where gpa=3.9",
        "update student_semester_gpa set is_deleted=true where roll_number='R-03'"),
    Case("session_fees", "session_fees",
        listOf(
            "insert into session_fees(session_id,shift,cadence) values ('ch_2023','MORNING','SEMESTER')",
            "insert into session_fees(session_id,shift,cadence) values ('ur_2023','MORNING','SEMESTER')",
            "insert into session_fees(session_id,shift,cadence) values ('ch_2024','MORNING','SEMESTER')",
        ), 3,
        "insert into session_fees(session_id,shift,cadence) values ('ur_2024','MORNING','SEMESTER')",
        "update session_fees set payment_note='UPD' where session_id='ch_2023'",
        "select count(*) from session_fees where paymentNote='UPD'",
        "update session_fees set is_deleted=true where session_id='ch_2024'"),
    Case("session_fee_heads", "session_fee_heads",
        listOf(
            "insert into session_fee_heads(session_id,shift,label,amount,position) values ('ch_2023','MORNING','Tuition',10000,0)",
            "insert into session_fee_heads(session_id,shift,label,amount,position) values ('ch_2023','MORNING','Library',500,1)",
            "insert into session_fee_heads(session_id,shift,label,amount,position) values ('ch_2023','MORNING','Victim',1,2)",
        ), 3,
        "insert into session_fee_heads(session_id,shift,label,amount,position) values ('ch_2023','MORNING','Lab',800,3)",
        "update session_fee_heads set amount=777 where label='Tuition'",
        "select count(*) from session_fee_heads where amount=777",
        "update session_fee_heads set is_deleted=true where label='Victim'"),
    Case("exam_paper_submissions", "exam_paper_submissions",
        listOf(
            "insert into exam_paper_submissions(session_id,semester,course_code,teacher_email,storage_path,file_name) values ('ch_2023',3,'GE-101','t1@x.pk','p/1.pdf','one.pdf')",
            "insert into exam_paper_submissions(session_id,semester,course_code,teacher_email,storage_path,file_name) values ('ch_2023',3,'GE-102','t1@x.pk','p/2.pdf','two.pdf')",
            "insert into exam_paper_submissions(session_id,semester,course_code,teacher_email,storage_path,file_name) values ('ch_2023',3,'GE-103','t1@x.pk','p/3.pdf','victim.pdf')",
        ), 3,
        "insert into exam_paper_submissions(session_id,semester,course_code,teacher_email,storage_path,file_name) values ('ch_2023',3,'GE-104','t1@x.pk','p/4.pdf','four.pdf')",
        "update exam_paper_submissions set file_name='UPD.pdf' where course_code='GE-101'",
        "select count(*) from exam_paper_submissions where fileName='UPD.pdf'",
        "update exam_paper_submissions set is_deleted=true where course_code='GE-103'"),
    Case("student_link_requests", "student_link_requests",
        listOf(
            "insert into student_link_requests(requested_by_email,roll_number_claimed,session_id) values ('s1@x.pk','R-01','ch_2023')",
            "insert into student_link_requests(requested_by_email,roll_number_claimed,session_id) values ('s2@x.pk','R-02','ch_2023')",
            "insert into student_link_requests(requested_by_email,roll_number_claimed,session_id) values ('s3@x.pk','R-03','ch_2023')",
        ), 3,
        "insert into student_link_requests(requested_by_email,roll_number_claimed,session_id) values ('s4@x.pk','R-04','ch_2023')",
        "update student_link_requests set message='UPD' where roll_number_claimed='R-01'",
        "select count(*) from student_link_requests where message='UPD'",
        "update student_link_requests set is_deleted=true where roll_number_claimed='R-03'"),
    Case("notifications", "notifications",
        listOf(
            "insert into notifications(title,body,target_role,created_by_email) values ('Hello','Body one','ALL','a1@x.pk')",
            "insert into notifications(title,body,target_role,created_by_email) values ('Exam','Body two','STUDENT','a1@x.pk')",
            "insert into notifications(title,body,target_role,created_by_email) values ('Victim','Body three','TEACHER','a1@x.pk')",
        ), 3,
        "insert into notifications(title,body,target_role,created_by_email) values ('Fresh','Body four','ALL','a1@x.pk')",
        "update notifications set title='UPD' where title='Hello'",
        "select count(*) from notifications where title='UPD'",
        "update notifications set is_deleted=true where title='Victim'",
        scopes = 3),
)

