package com.mbd.cmscommon.domain.model

import java.time.Instant

data class StudentProfile(
    val sessionId: String,
    val rollNumber: String,
    val name: String,
    val universityRollNo: String? = null,
    val registrationNo: String? = null,
    val fatherName: String? = null,
    val guardianName: String? = null,
    val cnicBform: String? = null,
    val dob: String? = null,
    val gender: String? = null,
    val phone: String? = null,
    val guardianPhone: String? = null,
    val personalEmail: String? = null,
    val currentAddress: String? = null,
    val permanentAddress: String? = null,
    val bloodGroup: String? = null,
    val domicile: String? = null,
    val religion: String? = null,
    val admissionDate: String? = null,
    val enrollmentStatus: String = "ACTIVE",
    val emergencyContactName: String? = null,
    val emergencyContactRelation: String? = null,
    val emergencyContactPhone: String? = null,
    val specialNeeds: String? = null,
    val isCr: Boolean = false,
    val isGr: Boolean = false,
    val linkedEmail: String = "",
    val gpa: Double? = null,
    val cgpa: Double? = null,
    val isActive: Boolean = true,
    val photoPath: String? = null,
    override val entityId: Long = 0L,
    override val createdAt: Instant = Instant.EPOCH,
    override val createdBy: String? = null,
    override val updatedAt: Instant = Instant.EPOCH,
    override val updatedBy: String? = null,
) : BaseEntity()
