-- Reusable subject pool: every course is now defined once (name, credit hours, subject type THEORY/LAB, PU's
-- own course category, outline) in subject_pool, keyed college-wide by course_code, instead of being duplicated
-- as a free-standing row per session+semester. session_subjects becomes a pure link table: which course codes
-- a session+semester teaches, and whether it's an elective there. Editing a pool subject (e.g. its outline)
-- updates it everywhere that course code is linked.
create type course_category as enum ('GENERAL', 'MAJOR', 'COMPULSORY', 'INTERDISCIPLINARY');

create table subject_pool (
  course_code   text primary key,
  name          text not null,
  credit_hours  int not null default 3,
  subject_type  subject_type not null default 'THEORY',
  course_type   course_category not null default 'MAJOR',
  outline       text,
  created_at    timestamptz not null default now(),
  created_by    text,
  updated_at    timestamptz not null default now(),
  updated_by    text,
  is_deleted    boolean not null default false,
  deleted_at    timestamptz,
  deleted_by    text
);

alter table subject_pool enable row level security;

create policy sel_subject_pool on subject_pool for select to authenticated using (true);
create policy ins_subject_pool on subject_pool for insert to authenticated with check (is_admin());
create policy upd_subject_pool on subject_pool for update to authenticated using (is_admin()) with check (is_admin());
create policy del_subject_pool on subject_pool for delete to authenticated using (is_admin());

create trigger trg_audit_subject_pool before insert or update on subject_pool
  for each row execute function fn_cms_audit_row();
create trigger trg_touch_subject_pool before update on subject_pool
  for each row execute function fn_touch_updated_at();

create index idx_subject_pool_updated_at on subject_pool(updated_at);

-- Seed the pool from whatever is already assigned to a session, so no existing row is orphaned once
-- session_subjects stops carrying its own name/credit_hours/subject_type/outline below.
insert into subject_pool (course_code, name, credit_hours, subject_type, outline, created_at, created_by, updated_at, updated_by)
select distinct on (course_code) course_code, name, credit_hours, subject_type, outline, created_at, created_by, updated_at, updated_by
from session_subjects
order by course_code, updated_at desc
on conflict (course_code) do nothing;

alter table session_subjects add constraint session_subjects_course_code_fkey
  foreign key (course_code) references subject_pool(course_code);

alter table session_subjects
  drop column name,
  drop column credit_hours,
  drop column subject_type,
  drop column outline;

-- Seed/overwrite the pool with the University of the Punjab's current BS scheme of studies
-- (pu.edu.pk/home/bos2_pro), scraped 2026-09-30, for every department this college teaches.
insert into subject_pool (course_code, name, credit_hours, subject_type, course_type)
values
('AHIR-101','International Relations (AH)',2,'THEORY','GENERAL'),
('AHIS-122','World History (AH)',2,'THEORY','GENERAL'),
('AHIS-416','History of Revivalist Movements in Islam (AH)',2,'THEORY','GENERAL'),
('AHPH-100','Fundamentals of Philosophy (AH)',2,'THEORY','GENERAL'),
('AI-101','Introduction to Artificial Intelligence',3,'THEORY','INTERDISCIPLINARY'),
('APAK-122','Pakistani Society and Culture (AH)',2,'THEORY','GENERAL'),
('APED-111','Introduction to Health and Physical Education (AH)',2,'THEORY','GENERAL'),
('APHL-122','Fundamentals of Philosophy (AH)',2,'THEORY','GENERAL'),
('APHY-352','Mathematical Methods of Physics-I',3,'THEORY','MAJOR'),
('APHY-353','Computational Physics-I',3,'THEORY','MAJOR'),
('BBA-101','Fundamentals of Accounting',3,'THEORY','MAJOR'),
('BBA-102','Fundamentals of Management',3,'THEORY','MAJOR'),
('BBA-111','Financial Accounting',3,'THEORY','MAJOR'),
('BBA-112','Introduction to Human Resource Management',3,'THEORY','MAJOR'),
('BBA-202','Principles of Marketing',3,'THEORY','MAJOR'),
('BBA-203','Fundamentals of Financial Management',3,'THEORY','MAJOR'),
('BBA-204','Principles of Auditing',3,'THEORY','MAJOR'),
('BBA-212','Marketing Management',3,'THEORY','MAJOR'),
('BBA-213','Cost & Management Accounting',3,'THEORY','MAJOR'),
('BBA-214','Behavioral Sciences for Management',3,'THEORY','MAJOR'),
('BBA-301','Financial Institutions and Markets',3,'THEORY','INTERDISCIPLINARY'),
('BBA-302','Corporate Governance and Business Ethics',3,'THEORY','MAJOR'),
('BBA-303','Business Research & Report Writing',3,'THEORY','MAJOR'),
('BBA-304','Performance Management',3,'THEORY','MAJOR'),
('BBA-314','Microeconomics',3,'THEORY','INTERDISCIPLINARY'),
('BBA-423','Investment Analysis and Portfolio Management',3,'THEORY','MAJOR'),
('BBA-431','Consumer Behaviour',3,'THEORY','MAJOR'),
('BBA-441','Strategic Human Resource Management',3,'THEORY','MAJOR'),
('BSIS-100','Introduction to the Topics of the Quran',3,'THEORY','MAJOR'),
('BSIS-101','Study of the Seerah of the Holy Prophet',3,'THEORY','MAJOR'),
('BSIS-102','Arabic Language I',3,'THEORY','MAJOR'),
('BSIS-103','History & Authenticity of Hadith',3,'THEORY','MAJOR'),
('BSIS-200','Arabic Language-II',3,'THEORY','MAJOR'),
('BSIS-201','Introduction to World Religions – I',3,'THEORY','MAJOR'),
('BSIS-202','Textual Study of Al-Quran–I',3,'THEORY','MAJOR'),
('BSIS-203','Textual Study of Islamic Fiqh Family Matters',3,'THEORY','MAJOR'),
('BSIS-204','Textual Study of al-Hadith-I',3,'THEORY','MAJOR'),
('BSIS-205','History and Principles of Tafseer',3,'THEORY','MAJOR'),
('BSIS-300','Arabic Through Qur’anic Text',3,'THEORY','MAJOR'),
('BSIS-301','Textual Study of Al-Quran–II',3,'THEORY','MAJOR'),
('BSIS-302','Islamic Economics-I',3,'THEORY','MAJOR'),
('BSIS-303','Usoolul-Fiqh',3,'THEORY','MAJOR'),
('BSIS-304','Uloom ul-Hadith',3,'THEORY','MAJOR'),
('BSIS-305','Textual Study of Al-Hadith-II',3,'THEORY','MAJOR'),
('BSIS-401','Islamic Economics-II',3,'THEORY','MAJOR'),
('BSIS-402','Al-Dawah wal-Irshaad- I',3,'THEORY','MAJOR'),
('BSIS-403','Uloom ul-Quran',3,'THEORY','MAJOR'),
('BSIS-404','Islamic Jurisprudence: Matters of Ibadat',3,'THEORY','MAJOR'),
('BSIS-406','Arabic Literature',3,'THEORY','MAJOR'),
('BSIS-407','Al-Dawah wal-Irshaad - II',3,'THEORY','MAJOR'),
('BSIS-408','Introduction to the Study of World Religions - II',3,'THEORY','MAJOR'),
('BSIS-409','Islām and Modern Social Thoughts',3,'THEORY','MAJOR'),
('BSU-101','Urdu Language: Formation and Evolution',3,'THEORY','MAJOR'),
('BSU-102','Poetic Genres: Introduction & Understanding',3,'THEORY','MAJOR'),
('BSU-103','Prose Genres: Introduction and Understanding',3,'THEORY','MAJOR'),
('BSU-104','Literary Terms',3,'THEORY','MAJOR'),
('BSU-201','Styles of Urdu Prose: Humor, Travelogue, Autobiography',3,'THEORY','MAJOR'),
('BSU-202','Research and Criticism: Basic Concepts',3,'THEORY','MAJOR'),
('BSU-203','Grammar and Composition',3,'THEORY','MAJOR'),
('BSU-204','Urdu Journalism, Magazines & Journals',3,'THEORY','MAJOR'),
('BSU-205','Urdu Theater and Drama',3,'THEORY','MAJOR'),
('BSU-206','Short Stories of the World',3,'THEORY','MAJOR'),
('BSU-301','Urdu Dastan and Novel: Themes and Art',3,'THEORY','MAJOR'),
('BSU-302','Thematic and Artistic Study of Urdu Ghazal',3,'THEORY','MAJOR'),
('BSU-304','Urdu Poem: Thematic and Artistic Study',3,'THEORY','MAJOR'),
('BSU-305','History of Urdu Literature: From Beginning to 19th Century',3,'THEORY','MAJOR'),
('BSU-306','Principles of Research and Editing',3,'THEORY','MAJOR'),
('BSU-402','Special Study of Iqbal',3,'THEORY','MAJOR'),
('BSU-403','Urdu Short Story',3,'THEORY','MAJOR'),
('BSU-404','Hisotry of Urdu Literature: 20th Century',3,'THEORY','MAJOR'),
('BSU-405','Comtemporary Poetic Literature',3,'THEORY','MAJOR'),
('BSU-406','Capstone Project/Research Work',3,'THEORY','MAJOR'),
('BSU-407','New Critical Theories',3,'THEORY','MAJOR'),
('BSU-408','Comtemporary Prose Literature',3,'THEORY','MAJOR'),
('BSU-409','Modern Urdu Novel',3,'THEORY','MAJOR'),
('BSU-410','Literary Critcism: West & Urdu Contexts',3,'THEORY','MAJOR'),
('CAPP-401','Capstone Project',3,'THEORY','MAJOR'),
('CC-110','Digital Logic Design',2,'THEORY','MAJOR'),
('CC-110L','Digital Logic Design Lab',1,'LAB','MAJOR'),
('CC-112','Programming Fundamentals',3,'THEORY','MAJOR'),
('CC-112L','Programming Fundamentals Lab',1,'LAB','MAJOR'),
('CC-210','Computer Organization and Assembly Language',2,'THEORY','MAJOR'),
('CC-210L','Computer Organization and Assembly Language (Lab)',1,'LAB','MAJOR'),
('CC-211','Object Oriented Programming',3,'THEORY','MAJOR'),
('CC-211L','Object Oriented Programming (Lab)',1,'LAB','MAJOR'),
('CC-212','Software Engineering',3,'THEORY','MAJOR'),
('CC-213','Data Structures',3,'THEORY','MAJOR'),
('CC-213L','Data Structures (Lab)',1,'LAB','MAJOR'),
('CC-214','Computer Networks',2,'THEORY','MAJOR'),
('CC-214L','Computer Networks Lab',1,'LAB','MAJOR'),
('CC-215','Database Systems',3,'THEORY','MAJOR'),
('CC-215L','Database Systems Lab',1,'LAB','MAJOR'),
('CC-310','Artificial Intelligence',2,'THEORY','MAJOR'),
('CC-310L','Artificial Intelligence (Lab)',1,'LAB','MAJOR'),
('CC-311','Operating Systems',2,'THEORY','MAJOR'),
('CC-311L','Operating Systems (Lab)',1,'LAB','MAJOR'),
('CC-312','Information Security',3,'THEORY','MAJOR'),
('CC-313','Analysis of Algorithms',3,'THEORY','MAJOR'),
('CHEM-101','Physical Chemistry-I',2,'THEORY','MAJOR'),
('CHEM-102','Physical Chemistry-I (Lab)',1,'LAB','MAJOR'),
('CHEM-103','Physical Chemistry-II Thermodynamics',3,'THEORY','MAJOR'),
('CHEM-116','Fundamental Concepts of Chemical Bonding',2,'THEORY','MAJOR'),
('CHEM-117','Fundamental Concepts of Chemical Bonding (Lab)',1,'LAB','MAJOR'),
('CHEM-131','Basic Organic Chemistry',2,'THEORY','MAJOR'),
('CHEM-132','Organic Chemistry Lab',1,'LAB','MAJOR'),
('CHEM-201','Chemical Kinetics',2,'THEORY','MAJOR'),
('CHEM-202','Physical Chemistry (Lab)',1,'LAB','MAJOR'),
('CHEM-216','Metallurgical Aspects of Inorganic Compounds',3,'THEORY','MAJOR'),
('CHEM-217','Chemistry of F-Block Elements',2,'THEORY','MAJOR'),
('CHEM-218','Inorganic Chemistry (Lab)',1,'LAB','MAJOR'),
('CHEM-231','Reaction Mechanism',3,'THEORY','MAJOR'),
('CHEM-232','Stereochemistry',2,'THEORY','MAJOR'),
('CHEM-233','Organic Chemistry (Lab)',1,'LAB','MAJOR'),
('CHEM-246','Introduction to Analytical Chemistry',2,'THEORY','MAJOR'),
('CHEM-261','Water Treatment and Cleansers',2,'THEORY','MAJOR'),
('CHEM-276','Introductory Biochemistry',2,'THEORY','MAJOR'),
('CHEM-291','Introduction to Green Chemistry',2,'THEORY','MAJOR'),
('CHEM-301','Electrochemistry',2,'THEORY','MAJOR'),
('CHEM-302','Physical Chemistry (Lab)',1,'LAB','MAJOR'),
('CHEM-316','Coordination Chemistry',2,'THEORY','MAJOR'),
('CHEM-317','Coordination Chemistry Lab',1,'LAB','MAJOR'),
('CHEM-331','UV & IR Spectroscopy',2,'THEORY','MAJOR'),
('CHEM-332','Organic Chemistry (Lab)',1,'LAB','MAJOR'),
('CHEM-346','Chromatographic Techniques-I',2,'THEORY','MAJOR'),
('CHEM-347','Basic Chromatographic Techniques (Lab)',1,'LAB','MAJOR'),
('CHEM-348','Analytical Separation Tools-I',2,'THEORY','MAJOR'),
('CHEM-349','Analytical Separation Tools-I Lab',1,'LAB','MAJOR'),
('CHEM-350','Introduction to Spectral and Separation Techniques',3,'THEORY','MAJOR'),
('CHEM-361','Unit Operations and basic Chemical industries',2,'THEORY','MAJOR'),
('CHEM-362','Applied Chemistry (Lab)',1,'LAB','MAJOR'),
('CHEM-363','Unit Processes and Raw Materials',2,'THEORY','MAJOR'),
('CHEM-364','Unit Processes and Raw Materials Lab',1,'LAB','MAJOR'),
('CHEM-365','Allied Chemical industries',3,'THEORY','MAJOR'),
('CHEM-376','Carbohydrate',2,'THEORY','MAJOR'),
('CHEM-377','Carbohydrate (Lab)',1,'LAB','MAJOR'),
('CHEM-378','Protein',2,'THEORY','MAJOR'),
('CHEM-379','Protein Lab',1,'LAB','MAJOR'),
('CHEM-380','Immunology',3,'THEORY','MAJOR'),
('CHEM-391','Introduction to Green Solvents',2,'THEORY','MAJOR'),
('CHEM-392','Green Solvents (Lab)',1,'LAB','MAJOR'),
('CHEM-393','Applications of Green Solvents',2,'THEORY','MAJOR'),
('CHEM-394','Applications of Green Solvents Lab',1,'LAB','MAJOR'),
('CHEM-395','Green Chemistry and Sustainable Development Goals',3,'THEORY','MAJOR'),
('CHEM-400','Fieldwork / Intership',3,'THEORY','MAJOR'),
('CHEM-499','Capstone Project',3,'THEORY','MAJOR'),
('CHEM246L','Introduction to Analytical Chemistry Lab',1,'LAB','MAJOR'),
('CHEM261L','Water Treatment and Cleansers Lab',1,'LAB','MAJOR'),
('CHEM276L','Introductory Biochemistry Lab',1,'LAB','MAJOR'),
('CHEM291L','Introduction to Green Chemistry Lab',1,'LAB','MAJOR'),
('DC-328','Parallel & Distributed Computing',2,'THEORY','MAJOR'),
('DC-328L','Parallel & Distributed Computing (Lab)',1,'LAB','MAJOR'),
('DI-322','Web Technologies',2,'THEORY','MAJOR'),
('DI-322L','Web Technologies (Lab)',1,'LAB','MAJOR'),
('ELL-101','Introduction to Literary Studies',3,'THEORY','MAJOR'),
('ELL-102','Literary Forms and Movements',3,'THEORY','MAJOR'),
('ELL-103','Classical Poetry',3,'THEORY','MAJOR'),
('ELL-104','Language Culture and Identity',3,'THEORY','MAJOR'),
('ELL-201','Classical and Renaissance Drama',3,'THEORY','MAJOR'),
('ELL-202','Introduction to Linguistics',3,'THEORY','MAJOR'),
('ELL-203','Discourse Studies',3,'THEORY','MAJOR'),
('ELL-204','Romantic and Victorian Poetry',3,'THEORY','MAJOR'),
('ELL-205','Rise of the Novel',3,'THEORY','MAJOR'),
('ELL-206','American Literature',3,'THEORY','MAJOR'),
('ELL-301','Twentieth Century British Literature Poetry and Drama',3,'THEORY','MAJOR'),
('ELL-302','Short Fictional Narratives',3,'THEORY','MAJOR'),
('ELL-303','Literary Theory and Practice I',3,'THEORY','MAJOR'),
('ELL-304','Modern Poetry',3,'THEORY','MAJOR'),
('ELL-305','Modern Drama',3,'THEORY','MAJOR'),
('ELL-306','Modern Novel',3,'THEORY','MAJOR'),
('GCCE-101','Civics and Community Engagement',2,'THEORY','GENERAL'),
('GCCE-201','Civics and Community Engagement',2,'THEORY','GENERAL'),
('GE-160','Applications of Information and Communication Technologies',2,'THEORY','GENERAL'),
('GE-160L','Applications of Information and Communication Technologies Lab',1,'LAB','GENERAL'),
('GE-162','Calculus & Analytical Geometry',3,'THEORY','MAJOR'),
('GE-167','Discrete Structures',3,'THEORY','GENERAL'),
('GE-169','Applied Physics',3,'THEORY','GENERAL'),
('GE-192','Introduction to Management',2,'THEORY','MAJOR'),
('GE-262','Professional Practices',2,'THEORY','GENERAL'),
('GENG-101','Functional English',3,'THEORY','GENERAL'),
('GENG-201','Expository Writing',3,'THEORY','GENERAL'),
('GENT-101','Entrepreneurship',2,'THEORY','GENERAL'),
('GICP-101','Ideology and Constitution of Pakistan',2,'THEORY','GENERAL'),
('GICT-201','Applications of Information and Communication Technologies',3,'THEORY','GENERAL'),
('GISL-101/GETH-101','Islamic Studies / Ethics (for Non-Muslims)',2,'THEORY','GENERAL'),
('GNAT-201','Basic Electronics',3,'THEORY','GENERAL'),
('GNS-101','Ecology (NS)',3,'THEORY','GENERAL'),
('GPST-201','Pakistan Studies.',2,'THEORY','GENERAL'),
('GQR-101','Quantitative Reasoning (I)',3,'THEORY','GENERAL'),
('GQR-201','Quantitative Reasoning (II)',3,'THEORY','GENERAL'),
('GSS-101','Introduction to Social Sciences (SS)',3,'THEORY','GENERAL'),
('HIS-103','Research Methodology',3,'THEORY','INTERDISCIPLINARY'),
('HIS-201','Muslim Nationalism in South Asia (1857-1906)',3,'THEORY','INTERDISCIPLINARY'),
('HIS-401','History of Umayyads and Abbasids',3,'THEORY','INTERDISCIPLINARY'),
('HQ-003N','Fehm-e-Quran-I',1,'THEORY','COMPULSORY'),
('HQ-004N','Fehm-e-Quran-II',1,'THEORY','COMPULSORY'),
('HQ-005','Tarjuma-e-Quran',0,'THEORY','COMPULSORY'),
('HQ-006','Tarjuma-e-Quran',1,'THEORY','COMPULSORY'),
('HQ-007','Tarjuma-e-Quran',0,'THEORY','COMPULSORY'),
('HQ-008','Tarjuma-e-Quran',1,'THEORY','COMPULSORY'),
('IDWS-302','Teaching of Urdu',3,'THEORY','INTERDISCIPLINARY'),
('IDWS-303','World Novel',3,'THEORY','INTERDISCIPLINARY'),
('INT-401','Fieldwork / Intership',3,'THEORY','MAJOR'),
('INTE-401','Fieldwork / Intership',3,'THEORY','MAJOR'),
('MATH-101','Single Variable Calculus',3,'THEORY','MAJOR'),
('MATH-102','Plane Curves & Analytic Geometry',3,'THEORY','MAJOR'),
('MATH-103','Introduction to Graph Theory',3,'THEORY','MAJOR'),
('MATH-104','Discrete Mathematics',3,'THEORY','MAJOR'),
('MATH-201','Multivariable Calculus',3,'THEORY','MAJOR'),
('MATH-202','Ordinary Differential Equations',3,'THEORY','MAJOR'),
('MATH-203','Number Theory',3,'THEORY','MAJOR'),
('MATH-204','Real Analysis',3,'THEORY','MAJOR'),
('MATH-205','Fundamentals of Mechanics',3,'THEORY','MAJOR'),
('MATH-206','Group Theory',3,'THEORY','MAJOR'),
('MATH-301','Complex Analysis',3,'THEORY','MAJOR'),
('MATH-302','Classical Mechanics',3,'THEORY','MAJOR'),
('MATH-303','Linear Algebra',3,'THEORY','MAJOR'),
('MATH-304','Partial Differential Equations',3,'THEORY','MAJOR'),
('MATH-305','Computational Tools',3,'THEORY','MAJOR'),
('MATH-306','Topology',3,'THEORY','MAJOR'),
('MATH-307','Advanced Analysis',3,'THEORY','MAJOR'),
('MATH-308','Tensor Analysis',3,'THEORY','MAJOR'),
('MATH-309','Rings and Modules',3,'THEORY','MAJOR'),
('MATH-310','Methods of Mathematical Physics',3,'THEORY','MAJOR'),
('MATH-311','Mathematical Computing with Python',3,'THEORY','MAJOR'),
('MATH-401','Functional Analysis',3,'THEORY','MAJOR'),
('MATH-402','Differential Geometry',3,'THEORY','MAJOR'),
('MATH-403','Numerical Analysis',3,'THEORY','MAJOR'),
('MATH-404','Operations Research',3,'THEORY','MAJOR'),
('MATH-405','Analytical Dynamics',3,'THEORY','MAJOR'),
('MATH-406','Numerical Methods with Computer Programming',3,'THEORY','MAJOR'),
('MD-001','Math Deficiency – I',3,'THEORY','GENERAL'),
('MD-002','Math Deficiency – II',3,'THEORY','GENERAL'),
('MPHY-101','Calculus-I',3,'THEORY','MAJOR'),
('MPHY-102','CALCULUS - II',3,'THEORY','MAJOR'),
('MPHY-111','Mechanics',3,'THEORY','MAJOR'),
('MPHY-112','WAVES AND OPTICS',3,'THEORY','MAJOR'),
('MPHY-161','PHYSICS LAB-1',1,'LAB','MAJOR'),
('MPHY-203','LINEAR ALGEBRA',3,'THEORY','MAJOR'),
('MPHY-204','Differential Equations',3,'THEORY','MAJOR'),
('MPHY-213','THERMAL PHYSICS',3,'THEORY','MAJOR'),
('MPHY-221','ELECTRICITY AND MAGNETISM',3,'THEORY','MAJOR'),
('MPHY-231','Modern Physics',3,'THEORY','MAJOR'),
('MPHY-251','Mathematical Methods',3,'THEORY','MAJOR'),
('MPHY-262','PHYSICS LAB II',1,'LAB','MAJOR'),
('MPHY-263','Physics Lab III',1,'LAB','MAJOR'),
('MPHY-314','Classical Mechanics',3,'THEORY','MAJOR'),
('MPHY-341','Solid State Physics-I',3,'THEORY','MAJOR'),
('MPHY-364','Physics Lab-IV',1,'LAB','MAJOR'),
('MPHY-371','Electornics-I',3,'THEORY','MAJOR'),
('MS-251','Probability and Statistics',3,'THEORY','MAJOR'),
('MS-252','Linear Algebra',3,'THEORY','MAJOR'),
('MS-253','Multivariable Calculus',3,'THEORY','MAJOR'),
('NDM-120','Fundamentals of Disaster Management (NS)',3,'THEORY','GENERAL'),
('NHPY-110','What is Science? (NS)',3,'THEORY','GENERAL'),
('NIS-105','Natural Science - II (NS)',3,'THEORY','GENERAL'),
('NPH-102','Fundamentals of Human Nutrition (NS)',3,'THEORY','GENERAL'),
('NPHY-120','Introduction to Physics(NS)',3,'THEORY','GENERAL'),
('NSW-106','Science Wonders Around Us (NS)',3,'THEORY','GENERAL'),
('NZ-116','Environmental Biology (NS)',2,'THEORY','GENERAL'),
('NZ-117','Lab. Environmental Biology (NS)',1,'LAB','GENERAL'),
('PS-101','Political Science: History and Foundational Philosophies',3,'THEORY','MAJOR'),
('PS-102','Political Science: Elements and Contemporary Discourses',3,'THEORY','MAJOR'),
('PS-111','Origins of Democracy and Democratic Institutionalism: Philosophical Approaches',3,'THEORY','MAJOR'),
('PS-112','The Science of Politics: Statecraft and Institutional Frameworks',3,'THEORY','MAJOR'),
('PS-201','Politics of the Developing World',3,'THEORY','MAJOR'),
('PS-202','Introduction to Geopolitics: Global, and Regional',3,'THEORY','MAJOR'),
('PS-203','Citizen and State: Understanding Fundamentals of Citizen Politics',3,'THEORY','MAJOR'),
('PS-251','Voting Elections Campaign and Media',3,'THEORY','MAJOR'),
('PS-252','Politics of Pakistan Historical and Comparative Perspective',3,'THEORY','MAJOR'),
('PS-253','Political System (Developed) UK & USA',3,'THEORY','MAJOR'),
('SS-101','Introduction to Economics (SS)',2,'THEORY','GENERAL'),
('SSOC-101','Introduction to Sociology (SS)',2,'THEORY','GENERAL'),
('UE-272','Introduction to Marketing',3,'THEORY','GENERAL'),
('ZOOL-101','Animal Diversity-I',2,'THEORY','MAJOR'),
('ZOOL-102','Lab. Animal Diversity-I',1,'LAB','MAJOR'),
('ZOOL-103','Cell Biology',2,'THEORY','MAJOR'),
('ZOOL-104','Lab. Cell Biology',1,'LAB','MAJOR'),
('ZOOL-105','Animal Diversity-II',2,'THEORY','MAJOR'),
('ZOOL-106','Lab. Animal Diversity-II',1,'LAB','MAJOR'),
('ZOOL-107','Biological Techniques',1,'THEORY','MAJOR'),
('ZOOL-108','Lab. Biological Techniques',2,'LAB','MAJOR'),
('ZOOL-201','Animal Diversity-III',2,'THEORY','MAJOR'),
('ZOOL-202','Lab. Animal Diversity-III',1,'LAB','MAJOR'),
('ZOOL-203','Animal Form & Function–I',2,'THEORY','MAJOR'),
('ZOOL-204','Lab. Animal Form & Function–I',1,'LAB','MAJOR'),
('ZOOL-205','Economic Zoology',2,'THEORY','MAJOR'),
('ZOOL-206','Lab. Economic Zoology',1,'LAB','MAJOR'),
('ZOOL-207','Ecology',2,'THEORY','MAJOR'),
('ZOOL-208','Ecology (Lab)',1,'LAB','MAJOR'),
('ZOOL-209','Animal Form And Function–II',2,'THEORY','MAJOR'),
('ZOOL-210','Animal Form And Function–II (Lab)',1,'LAB','MAJOR'),
('ZOOL-211','Animal Behavior',2,'THEORY','MAJOR'),
('ZOOL-212','Animal Behavior (Lab)',1,'LAB','MAJOR'),
('ZOOL-213','Biochemistry-I',2,'THEORY','MAJOR'),
('ZOOL-214','Biochemistry-I (Lab)',1,'LAB','MAJOR'),
('ZOOL-301','Entomology',2,'THEORY','INTERDISCIPLINARY'),
('ZOOL-302','Lab. Entomology',1,'LAB','INTERDISCIPLINARY'),
('ZOOL-303','Environmental Biology',2,'THEORY','INTERDISCIPLINARY'),
('ZOOL-304','Lab. Environmental Biology',1,'LAB','INTERDISCIPLINARY'),
('ZOOL-305','Biochemistry-II',2,'THEORY','MAJOR'),
('ZOOL-306','Lab. Biochemistry-II',1,'LAB','MAJOR'),
('ZOOL-307','Physiology-I',2,'THEORY','MAJOR'),
('ZOOL-308','Lab. Physiology-I',1,'LAB','MAJOR'),
('ZOOL-309','Genetics-I',2,'THEORY','MAJOR'),
('ZOOL-310','Lab. Genetics-I',1,'LAB','MAJOR'),
('ZOOL-311','General Microbiology',2,'THEORY','INTERDISCIPLINARY'),
('ZOOL-312','Lab. General Microbiology',1,'LAB','INTERDISCIPLINARY'),
('ZOOL-313','Research Methodology',3,'THEORY','INTERDISCIPLINARY'),
('ZOOL-314','Developmental Biology',2,'THEORY','MAJOR'),
('ZOOL-315','Lab. Developmental Biology',1,'LAB','MAJOR'),
('ZOOL-316','Genetics-II',2,'THEORY','MAJOR'),
('ZOOL-317','Lab. Genetics-II',1,'LAB','MAJOR'),
('ZOOL-318','Wildlife',2,'THEORY','MAJOR'),
('ZOOL-319','Lab. Wildlife',1,'LAB','MAJOR'),
('ZOOL-320','Physiology-II',2,'THEORY','MAJOR'),
('ZOOL-321','Lab. Physiology-II',1,'LAB','MAJOR'),
('ZOOL-401','Fieldwork / Intership',3,'THEORY','MAJOR'),
('ZOOL-402','Analysis of Development',2,'THEORY','MAJOR'),
('ZOOL-403','Lab. Analysis of Development',1,'LAB','MAJOR'),
('ZOOL-404','Principles of Systematics',2,'THEORY','MAJOR'),
('ZOOL-405','Lab. Principles of Systematics',1,'LAB','MAJOR'),
('ZOOL-406','Principles of Paleontology',2,'THEORY','MAJOR'),
('ZOOL-407','Lab. Principles of Paleontology',1,'LAB','MAJOR'),
('ZOOL-408','Molecular Biology',2,'THEORY','MAJOR'),
('ZOOL-409','Lab. Molecular Biology',1,'LAB','MAJOR'),
('ZOOL-410','Industrial Biotechnology',2,'THEORY','MAJOR'),
('ZOOL-411','Lab. Industrial Biotechnology',1,'LAB','MAJOR'),
('ZOOL-412','Capstone Project',3,'THEORY','MAJOR'),
('ZOOL-413','Bioinformatics',1,'THEORY','MAJOR'),
('ZOOL-414','Lab. Bioinformatics',2,'LAB','MAJOR'),
('ZOOL-415','Applied Fisheries',2,'THEORY','MAJOR'),
('ZOOL-417','Evolution',2,'THEORY','MAJOR'),
('ZOOL-418','Lab. Evolution',1,'LAB','MAJOR'),
('ZOOL-419','Zoogeography',2,'THEORY','MAJOR'),
('ZOOL-420','Lab. Zoogeography',1,'LAB','MAJOR')
on conflict (course_code) do update set
  name = excluded.name, credit_hours = excluded.credit_hours, subject_type = excluded.subject_type, course_type = excluded.course_type,
  updated_at = now();

-- Replace every session's curriculum with the PU scheme: for each department, the same course list applies
-- to every intake (2023-2026) across all 8 semesters, and to the MA-Replacement variant of a department's
-- session for semesters 5-8 only (that program starts students directly at semester 5).
do $$
begin
  create temp table pu_scheme (dept text, semester int, course_code text, is_elective boolean) on commit drop;
  insert into pu_scheme values
('bba',1,'GENG-101',false),
('bba',1,'GCCE-101',false),
('bba',1,'GISL-101/GETH-101',false),
('bba',1,'GNS-101',false),
('bba',1,'BBA-101',false),
('bba',1,'BBA-102',false),
('bba',2,'AHIR-101',false),
('bba',2,'GQR-101',false),
('bba',2,'GENT-101',false),
('bba',2,'GICP-101',false),
('bba',2,'BBA-112',false),
('bba',2,'BBA-111',false),
('bba',3,'GICT-201',false),
('bba',3,'GENG-201',false),
('bba',3,'GPST-201',false),
('bba',3,'BBA-202',false),
('bba',3,'BBA-203',false),
('bba',3,'BBA-204',false),
('bba',3,'HQ-003N',false),
('bba',4,'GQR-201',false),
('bba',4,'BBA-212',false),
('bba',4,'BBA-213',false),
('bba',4,'BBA-214',false),
('bba',4,'HQ-004N',false),
('bba',5,'BBA-314',false),
('bba',5,'BBA-301',false),
('bba',5,'BBA-302',false),
('bba',5,'BBA-303',false),
('bba',5,'BBA-304',false),
('bba',5,'HQ-005',false),
('bba',5,'BBA-423',false),
('bba',5,'BBA-431',false),
('bba',5,'BBA-441',false),
('bba',6,'HQ-006',false),
('bba',7,'HQ-007',false),
('bba',8,'HQ-008',false),
('chem',1,'GENG-101',false),
('chem',1,'GCCE-101',false),
('chem',1,'GISL-101/GETH-101',false),
('chem',1,'CHEM-116',false),
('chem',1,'CHEM-101',false),
('chem',1,'NSW-106',false),
('chem',1,'CHEM-117',false),
('chem',1,'CHEM-102',false),
('chem',2,'AHIS-122',false),
('chem',2,'GQR-101',false),
('chem',2,'GENT-101',false),
('chem',2,'GICP-101',false),
('chem',2,'CHEM-131',false),
('chem',2,'CHEM-103',false),
('chem',2,'CHEM-132',false),
('chem',3,'GICT-201',false),
('chem',3,'GPST-201',false),
('chem',3,'GENG-201',false),
('chem',3,'CHEM-216',false),
('chem',3,'CHEM-231',false),
('chem',3,'CHEM-246',true),
('chem',3,'CHEM246L',true),
('chem',3,'CHEM-261',true),
('chem',3,'CHEM261L',true),
('chem',3,'CHEM-276',true),
('chem',3,'CHEM276L',true),
('chem',3,'CHEM-291',true),
('chem',3,'CHEM291L',true),
('chem',3,'HQ-003N',true),
('chem',4,'GQR-201',false),
('chem',4,'CHEM-201',false),
('chem',4,'CHEM-202',false),
('chem',4,'CHEM-217',false),
('chem',4,'CHEM-218',false),
('chem',4,'CHEM-232',false),
('chem',4,'CHEM-233',false),
('chem',4,'HQ-004N',false),
('chem',5,'CHEM-301',false),
('chem',5,'CHEM-302',false),
('chem',5,'CHEM-331',false),
('chem',5,'CHEM-332',false),
('chem',5,'CHEM-346',true),
('chem',5,'CHEM-347',true),
('chem',5,'CHEM-361',true),
('chem',5,'CHEM-362',true),
('chem',5,'CHEM-376',true),
('chem',5,'CHEM-377',true),
('chem',5,'CHEM-391',true),
('chem',5,'CHEM-392',true),
('chem',5,'HQ-005',true),
('chem',6,'HQ-006',false),
('chem',7,'CHEM-400',false),
('chem',7,'HQ-007',false),
('chem',8,'CHEM-499',false),
('chem',8,'HQ-008',false),
('chem',6,'CHEM-350',false),
('chem',6,'CHEM-348',false),
('chem',6,'CHEM-349',false),
('chem',6,'CHEM-316',false),
('chem',6,'CHEM-317',false),
('chem',6,'CHEM-363',false),
('chem',6,'CHEM-364',false),
('chem',6,'CHEM-365',false),
('chem',6,'CHEM-378',false),
('chem',6,'CHEM-379',false),
('chem',6,'CHEM-380',false),
('chem',6,'CHEM-393',false),
('chem',6,'CHEM-394',false),
('chem',6,'CHEM-395',false),
('eng',1,'GENG-101',false),
('eng',1,'GCCE-101',false),
('eng',1,'GISL-101/GETH-101',false),
('eng',1,'ELL-102',false),
('eng',1,'ELL-101',false),
('eng',1,'NPH-102',false),
('eng',2,'AHPH-100',false),
('eng',2,'GQR-101',false),
('eng',2,'GENT-101',false),
('eng',2,'GICP-101',false),
('eng',2,'ELL-202',false),
('eng',2,'ELL-103',false),
('eng',3,'GICT-201',false),
('eng',3,'GENG-201',false),
('eng',3,'ELL-203',false),
('eng',3,'ELL-104',false),
('eng',3,'ELL-201',false),
('eng',3,'GPST-201',false),
('eng',3,'HQ-003N',false),
('eng',4,'SSOC-101',false),
('eng',4,'GQR-201',false),
('eng',4,'ELL-204',false),
('eng',4,'ELL-205',false),
('eng',4,'ELL-206',false),
('eng',4,'HQ-004N',false),
('eng',5,'ELL-301',false),
('eng',5,'ELL-302',false),
('eng',5,'ELL-303',false),
('eng',5,'HQ-005',false),
('eng',6,'AI-101',false),
('eng',6,'ELL-304',false),
('eng',6,'ELL-305',false),
('eng',6,'ELL-306',false),
('eng',6,'HQ-006',false),
('eng',7,'HQ-007',false),
('eng',8,'HQ-008',false),
('it',1,'GENG-101',false),
('it',1,'GISL-101/GETH-101',false),
('it',1,'CC-110',false),
('it',1,'CC-110L',false),
('it',1,'GE-169',false),
('it',1,'MD-001',false),
('it',1,'GE-160',false),
('it',1,'GE-160L',false),
('it',1,'GPST-201',false),
('it',2,'CC-112L',false),
('it',2,'CC-112',false),
('it',2,'GENG-201',false),
('it',2,'MD-002',false),
('it',2,'CC-214',false),
('it',2,'GE-167',false),
('it',2,'UE-272',false),
('it',2,'CC-214L',false),
('it',3,'CC-210',false),
('it',3,'CC-210L',false),
('it',3,'CC-211',false),
('it',3,'CC-211L',false),
('it',3,'CC-212',false),
('it',3,'CC-215',false),
('it',3,'CC-215L',false),
('it',3,'GE-162',false),
('it',3,'GPST-201',false),
('it',3,'HQ-003N',false),
('it',4,'CC-213',false),
('it',4,'CC-213L',false),
('it',4,'CC-311',false),
('it',4,'CC-312',false),
('it',4,'GE-192',false),
('it',4,'MS-251',false),
('it',4,'MS-253',false),
('it',4,'CC-311L',false),
('it',4,'HQ-004N',false),
('it',5,'CC-310',false),
('it',5,'CC-310L',false),
('it',5,'CC-313',false),
('it',5,'DC-328',false),
('it',5,'DC-328L',false),
('it',5,'DI-322',false),
('it',5,'DI-322L',false),
('it',5,'MS-252',false),
('it',5,'GE-262',false),
('it',5,'HQ-005',false),
('it',6,'HQ-006',false),
('it',7,'HQ-007',false),
('it',8,'HQ-008',false),
('isl',1,'GENG-101',false),
('isl',1,'GCCE-101',false),
('isl',1,'GISL-101/GETH-101',false),
('isl',1,'BSIS-100',false),
('isl',1,'BSIS-101',false),
('isl',1,'NIS-105',false),
('isl',2,'AHIS-416',false),
('isl',2,'GQR-101',false),
('isl',2,'GENT-101',false),
('isl',2,'GICP-101',false),
('isl',2,'BSIS-103',false),
('isl',2,'BSIS-102',false),
('isl',3,'GICT-201',false),
('isl',3,'GENG-201',false),
('isl',3,'BSIS-202',false),
('isl',3,'BSIS-201',false),
('isl',3,'BSIS-200',false),
('isl',3,'GPST-201',false),
('isl',3,'HQ-003N',false),
('isl',4,'GQR-201',false),
('isl',4,'BSIS-205',false),
('isl',4,'BSIS-204',false),
('isl',4,'BSIS-203',false),
('isl',4,'HQ-004N',false),
('isl',5,'HIS-401',false),
('isl',5,'BSIS-302',false),
('isl',5,'BSIS-301',false),
('isl',5,'BSIS-300',false),
('isl',5,'HQ-005',false),
('isl',6,'HIS-103',false),
('isl',6,'HIS-201',false),
('isl',6,'BSIS-305',false),
('isl',6,'BSIS-304',false),
('isl',6,'BSIS-303',false),
('isl',6,'HQ-006',false),
('isl',7,'BSIS-404',false),
('isl',7,'BSIS-403',false),
('isl',7,'BSIS-402',false),
('isl',7,'BSIS-401',false),
('isl',7,'HQ-007',false),
('isl',8,'BSIS-409',false),
('isl',8,'BSIS-408',false),
('isl',8,'BSIS-407',false),
('isl',8,'BSIS-406',false),
('isl',8,'HQ-008',false),
('math',1,'GENG-101',false),
('math',1,'MATH-101',false),
('math',1,'GQR-101',false),
('math',1,'GICP-101',false),
('math',1,'AHPH-100',false),
('math',1,'SS-101',false),
('math',2,'GCCE-101',false),
('math',2,'GISL-101/GETH-101',false),
('math',2,'GENT-101',false),
('math',2,'MATH-103',false),
('math',2,'MATH-102',false),
('math',2,'MATH-104',false),
('math',3,'GENG-201',false),
('math',3,'MATH-203',false),
('math',3,'MATH-202',false),
('math',3,'MATH-201',false),
('math',3,'GPST-201',false),
('math',3,'NPHY-120',false),
('math',3,'HQ-003N',false),
('math',4,'GICT-201',false),
('math',4,'GQR-201',false),
('math',4,'MATH-206',false),
('math',4,'MATH-205',false),
('math',4,'MATH-204',false),
('math',4,'HQ-004N',false),
('math',5,'MATH-306',false),
('math',5,'MATH-305',false),
('math',5,'MATH-304',false),
('math',5,'MATH-303',false),
('math',5,'MATH-302',false),
('math',5,'HQ-005',false),
('math',5,'MATH-301',false),
('math',6,'MATH-311',false),
('math',6,'MATH-310',false),
('math',6,'MATH-309',false),
('math',6,'MATH-308',false),
('math',6,'MATH-307',false),
('math',6,'HQ-006',false),
('math',7,'INTE-401',false),
('math',7,'MATH-403',false),
('math',7,'MATH-402',false),
('math',7,'HQ-007',false),
('math',7,'MATH-401',false),
('math',8,'CAPP-401',false),
('math',8,'MATH-406',false),
('math',8,'MATH-405',false),
('math',8,'HQ-008',false),
('math',8,'MATH-404',false),
('phy',1,'GENG-101',false),
('phy',1,'GISL-101/GETH-101',false),
('phy',1,'APHL-122',false),
('phy',1,'GQR-101',false),
('phy',1,'MPHY-101',false),
('phy',1,'MPHY-111',false),
('phy',2,'GSS-101',false),
('phy',2,'GQR-201',false),
('phy',2,'GICP-101',false),
('phy',2,'MPHY-112',false),
('phy',2,'MPHY-102',false),
('phy',2,'MPHY-161',false),
('phy',3,'GICT-201',false),
('phy',3,'GENG-201',false),
('phy',3,'GPST-201',false),
('phy',3,'MPHY-262',false),
('phy',3,'MPHY-221',false),
('phy',3,'MPHY-213',false),
('phy',3,'MPHY-203',false),
('phy',3,'HQ-003N',false),
('phy',4,'GCCE-201',false),
('phy',4,'GNAT-201',false),
('phy',4,'MPHY-204',false),
('phy',4,'MPHY-231',false),
('phy',4,'MPHY-251',false),
('phy',4,'MPHY-263',false),
('phy',4,'HQ-004N',false),
('phy',5,'APHY-352',false),
('phy',5,'APHY-353',false),
('phy',5,'MPHY-314',false),
('phy',5,'MPHY-341',false),
('phy',5,'MPHY-364',false),
('phy',5,'MPHY-371',false),
('phy',5,'HQ-005',false),
('phy',6,'HQ-006',false),
('phy',7,'HQ-007',false),
('phy',8,'HQ-008',false),
('pol',1,'GENG-101',false),
('pol',1,'GCCE-101',false),
('pol',1,'GISL-101/GETH-101',false),
('pol',1,'PS-102',false),
('pol',1,'PS-101',false),
('pol',1,'NDM-120',false),
('pol',2,'APAK-122',false),
('pol',2,'GQR-101',false),
('pol',2,'GENT-101',false),
('pol',2,'GICP-101',false),
('pol',2,'PS-111',false),
('pol',2,'PS-112',false),
('pol',3,'GICT-201',false),
('pol',3,'GENG-201',false),
('pol',3,'PS-203',false),
('pol',3,'PS-202',false),
('pol',3,'PS-201',false),
('pol',3,'GPST-201',false),
('pol',3,'HQ-003N',false),
('pol',4,'GQR-201',false),
('pol',4,'PS-251',false),
('pol',4,'PS-252',false),
('pol',4,'PS-253',false),
('pol',4,'HQ-004N',false),
('pol',5,'HQ-005',false),
('pol',6,'HQ-006',false),
('pol',7,'HQ-007',false),
('pol',8,'HQ-008',false),
('urdu',1,'GENG-101',false),
('urdu',1,'GCCE-101',false),
('urdu',1,'GISL-101/GETH-101',false),
('urdu',1,'BSU-102',false),
('urdu',1,'BSU-101',false),
('urdu',1,'NHPY-110',false),
('urdu',2,'GQR-101',false),
('urdu',2,'GENT-101',false),
('urdu',2,'GICP-101',false),
('urdu',2,'BSU-104',false),
('urdu',2,'BSU-103',false),
('urdu',3,'GICT-201',false),
('urdu',3,'GENG-201',false),
('urdu',3,'BSU-203',false),
('urdu',3,'BSU-201',false),
('urdu',3,'BSU-202',false),
('urdu',3,'GPST-201',false),
('urdu',3,'HQ-003N',false),
('urdu',4,'GQR-201',false),
('urdu',4,'BSU-206',false),
('urdu',4,'BSU-205',false),
('urdu',4,'BSU-204',false),
('urdu',4,'HQ-004N',false),
('urdu',5,'BSU-302',false),
('urdu',5,'BSU-301',false),
('urdu',5,'HQ-005',false),
('urdu',6,'IDWS-303',false),
('urdu',6,'IDWS-302',false),
('urdu',6,'BSU-306',false),
('urdu',6,'BSU-305',false),
('urdu',6,'BSU-304',false),
('urdu',6,'HQ-006',false),
('urdu',7,'INT-401',false),
('urdu',7,'BSU-405',false),
('urdu',7,'BSU-404',false),
('urdu',7,'BSU-403',false),
('urdu',7,'BSU-402',false),
('urdu',7,'HQ-007',false),
('urdu',8,'BSU-406',false),
('urdu',8,'BSU-410',false),
('urdu',8,'BSU-409',false),
('urdu',8,'BSU-408',false),
('urdu',8,'BSU-407',false),
('urdu',8,'HQ-008',false),
('zoo',1,'GENG-101',false),
('zoo',1,'GCCE-101',false),
('zoo',1,'GISL-101/GETH-101',false),
('zoo',1,'ZOOL-104',false),
('zoo',1,'ZOOL-103',false),
('zoo',1,'ZOOL-101',false),
('zoo',1,'ZOOL-102',false),
('zoo',1,'NZ-116',false),
('zoo',1,'NZ-117',false),
('zoo',2,'APED-111',false),
('zoo',2,'GQR-101',false),
('zoo',2,'GENT-101',false),
('zoo',2,'GICP-101',false),
('zoo',2,'ZOOL-108',false),
('zoo',2,'ZOOL-107',false),
('zoo',2,'ZOOL-105',false),
('zoo',2,'ZOOL-106',false),
('zoo',3,'GICT-201',false),
('zoo',3,'GENG-201',false),
('zoo',3,'ZOOL-205',false),
('zoo',3,'ZOOL-204',false),
('zoo',3,'ZOOL-203',false),
('zoo',3,'ZOOL-201',false),
('zoo',3,'ZOOL-202',false),
('zoo',3,'ZOOL-206',false),
('zoo',3,'GPST-201',false),
('zoo',3,'HQ-003N',false),
('zoo',4,'GQR-201',false),
('zoo',4,'ZOOL-207',false),
('zoo',4,'ZOOL-208',false),
('zoo',4,'ZOOL-209',false),
('zoo',4,'ZOOL-210',false),
('zoo',4,'ZOOL-211',false),
('zoo',4,'ZOOL-212',false),
('zoo',4,'ZOOL-213',false),
('zoo',4,'ZOOL-214',false),
('zoo',4,'HQ-004N',false),
('zoo',5,'ZOOL-302',false),
('zoo',5,'ZOOL-301',false),
('zoo',5,'ZOOL-309',false),
('zoo',5,'ZOOL-308',false),
('zoo',5,'HQ-005',false),
('zoo',5,'ZOOL-303',false),
('zoo',5,'ZOOL-304',false),
('zoo',5,'ZOOL-305',false),
('zoo',5,'ZOOL-306',false),
('zoo',5,'ZOOL-307',false),
('zoo',5,'ZOOL-310',false),
('zoo',6,'ZOOL-312',false),
('zoo',6,'ZOOL-311',false),
('zoo',6,'ZOOL-316',false),
('zoo',6,'ZOOL-315',false),
('zoo',6,'ZOOL-314',false),
('zoo',6,'HQ-006',false),
('zoo',6,'ZOOL-313',false),
('zoo',6,'ZOOL-317',false),
('zoo',6,'ZOOL-318',false),
('zoo',6,'ZOOL-319',false),
('zoo',6,'ZOOL-320',false),
('zoo',6,'ZOOL-321',false),
('zoo',7,'ZOOL-401',false),
('zoo',7,'ZOOL-405',false),
('zoo',7,'ZOOL-404',false),
('zoo',7,'ZOOL-403',false),
('zoo',7,'ZOOL-402',false),
('zoo',7,'HQ-007',false),
('zoo',7,'ZOOL-406',false),
('zoo',7,'ZOOL-407',false),
('zoo',7,'ZOOL-408',false),
('zoo',7,'ZOOL-409',false),
('zoo',7,'ZOOL-410',false),
('zoo',7,'ZOOL-411',false),
('zoo',8,'ZOOL-412',false),
('zoo',8,'ZOOL-415',false),
('zoo',8,'ZOOL-414',false),
('zoo',8,'ZOOL-413',false),
('zoo',8,'HQ-008',false),
('zoo',8,'ZOOL-417',false),
('zoo',8,'ZOOL-418',false),
('zoo',8,'ZOOL-419',false),
('zoo',8,'ZOOL-420',false);

  create temp table dept_sessions (dept text, session_id text, is_ma boolean) on commit drop;
  insert into dept_sessions (dept, session_id, is_ma)
  select d.dept_id, s.session_id, s.program_type = 'MA_REPLACEMENT'
  from academic_sessions s join departments d on d.dept_id = s.dept_id
  where not s.is_deleted and d.dept_id in ('bba','chem','eng','it','isl','math','phy','pol','urdu','zoo');

  -- Drop this session's course codes the PU scheme no longer includes (a session's MA-Replacement
  -- semesters 1-4 are left untouched -- the scheme has nothing to say about them).
  update session_subjects ss set is_deleted = true
  from dept_sessions ds
  where ss.session_id = ds.session_id
    and not ss.is_deleted
    and (not ds.is_ma or ss.semester >= 5)
    and not exists (
      select 1 from pu_scheme p
      where p.dept = ds.dept and p.semester = ss.semester and p.course_code = ss.course_code
    );

  insert into session_subjects (session_id, semester, course_code, is_elective)
  select ds.session_id, p.semester, p.course_code, p.is_elective
  from pu_scheme p
  join dept_sessions ds on ds.dept = p.dept
  where not ds.is_ma or p.semester >= 5
  on conflict (session_id, semester, course_code) do update
    set is_elective = excluded.is_elective, is_deleted = false, deleted_at = null, deleted_by = null;
end $$;
